serviceAccount:
  create: true
  name: fluent-bit-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::559050241687:role/fluentbit-irsa-role

cloudwatch:
  enabled: true
  region: us-east-1
  logGroupName: /eks/app
  logStreamPrefix: fluent-
  logKey: log

output:
  cloudwatch:
    enabled: true
    region: us-east-1
    logGroupName: /eks/app
    logStreamPrefix: fluent-

  elasticsearch:
    enabled: false
  es:
    enabled: false
  forward:
    enabled: false
  http:
    enabled: false
  kafka:
    enabled: false

input:
  tail:
    enabled: true
    path: /var/log/containers/*.log
    parser: docker
    tag: kube.*
    refresh_interval: 5
    rotate_wait: 30
    mem_buf_limit: 5MB
    skip_long_lines: On
    db: /tail-db/tail-containers-state.db
    db_sync: normal

filter:
  kubernetes:
    enabled: true
    match: kube.*
    merge_log: On
    merge_log_key: log
    keep_log: Off
