apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: ghcr.io/jeffmeager/tasky:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ghcr-pull-secret
