apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      serviceAccountName: webapp-sa   # Allows access to Secrets Manager (if needed)
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: webapp
          image: ghcr.io/jeffmeager/tasky:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: webapp-secrets
                  key: mongodb-uri
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: webapp-secrets
                  key: secret-key
