apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  #- 144.6.153.44/32
  - 0.0.0.0/0

  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: webapp
